name: 'GitHub Actions Science Online Bot'

on:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Pull and push repo'
        run: bash ./startup.sh
        env: 
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
